# -*- coding: utf-8 -*-
"""oasis infobyte BMI calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vR94UT9WTCZwabNq4FUxbgXyuQO5Ht8d
"""

height = float(input('enter height in meters: '))
weight = float(input('enter weight in kilograms: '))
def BMI(height,weight):
  bmi = weight/(height**2)
  if(bmi<16):
    return 'severely underweight', bmi
  elif (bmi>=16 and bmi<18.5):
     return 'underweight', bmi
  elif(bmi>=18.5 and bmi<25):
    return 'healthy', bmi
  elif (bmi>=25 and bmi<30):
    return 'overweight', bmi
  elif(bmi>=30):
    return 'obese',bmi

quote,bmi=BMI(height,weight)
print("your bmi is: {} and you are :{}".format(bmi,quote))