# -*- coding: utf-8 -*-
"""oasis infobyte weather report

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-K_YX4iBmSMgoS5CilNOYFJb12Fmj-ss
"""

import requests
import json
def get_weather(api_key, location):
    base_url = "https://api.openweathermap.org/data/2.5/weather"
    params = {
        "q": location,
        "appid": api_key,
        "units": "metric"
    }
    try:
        response = requests.get(base_url, params=params)
        data = response.json()

        if data["cod"] == 200:
            # Extract weather data
            temperature = data["main"]["temp"]
            humidity = data["main"]["humidity"]
            weather_condition = data["weather"][0]["description"]

            # Print weather information
            print(f"Weather in {location}:")
            print(f"Temperature: {temperature}°C")
            print(f"Humidity: {humidity}%")
            print(f"Conditions: {weather_condition}")
        else:
            print(f"Error: {data['message']}")

    except requests.exceptions.RequestException:
        print("Failed to connect to the weather service")
    except json.JSONDecodeError:
        print("Failed to parse the weather data")
if __name__ == "__main__":
    api_key = "c3b3100687e438922607c3e1fe453208"
    location = input("Enter a city or ZIP code: ")
    get_weather(api_key, location)